name: Deploy to EC2

on:
  push:
    branches: [ main ]

env:
  DOCKER_IMAGE: ptks27/social-media-app
  EC2_HOST: ec2-52-196-18-167.ap-northeast-1.compute.amazonaws.com
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ${{ env.DOCKER_IMAGE }}:latest
        
    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ env.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          docker pull ${{ env.DOCKER_IMAGE }}:latest
          docker stop app-container || true
          docker rm app-container || true
          docker run -d \
            --name app-container \
            -p 3000:3000 \
            --restart unless-stopped \
            -e POSTGRES_URL="${{ secrets.POSTGRES_URL }}" \
            -e POSTGRES_PRISMA_URL="${{ secrets.POSTGRES_PRISMA_URL }}" \
            -e POSTGRES_URL_NON_POOLING="${{ secrets.POSTGRES_URL_NON_POOLING }}" \
            -e POSTGRES_USER="${{ secrets.POSTGRES_USER }}" \
            -e POSTGRES_HOST="${{ secrets.POSTGRES_HOST }}" \
            -e POSTGRES_PASSWORD="${{ secrets.POSTGRES_PASSWORD }}" \
            -e POSTGRES_DATABASE="${{ secrets.POSTGRES_DATABASE }}" \
            -e GOOGLE_CLIENT_ID="${{ secrets.GOOGLE_CLIENT_ID }}" \
            -e GOOGLE_CLIENT_SECRET="${{ secrets.GOOGLE_CLIENT_SECRET }}" \
            -e UPLOADTHING_SECRET="${{ secrets.UPLOADTHING_SECRET }}" \
            -e NEXT_PUBLIC_UPLOADTHING_APP_ID="${{ secrets.NEXT_PUBLIC_UPLOADTHING_APP_ID }}" \
            -e NEXT_PUBLIC_STREAM_KEY="${{ secrets.NEXT_PUBLIC_STREAM_KEY }}" \
            -e STREAM_SECRET="${{ secrets.STREAM_SECRET }}" \
            -e CRON_SECRET="${{ secrets.CRON_SECRET }}" \
            -e NEXT_PUBLIC_BASE_URL="${{ secrets.NEXT_PUBLIC_BASE_URL }}" \
            ${{ env.DOCKER_IMAGE }}:latest 